apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: demo-app
spec:
  project: default
  source:
    repoURL: https://github.com/smutoni2022/spacelift-argocd-helm-demo
    targetRevision: HEAD
    path: demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default