apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: default
spec:
  project: default
  sources:
  - repoURL: https://github.com/smutoni2022/spacelift-argocd-helm-demo
    targetRevision: HEAD
    path: demo-app
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app